# Generated by Django 3.1.2 on 2020-11-08 14:21

import brackets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrption', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FIFATeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='FIFA Team Name', max_length=100, unique=True)),
                ('team_avatar', models.ImageField(upload_to=brackets.models.img_upload_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fixture Name', max_length=180, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description', max_length=180, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fixture Type Name', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_scheduled', models.DateField(blank=True, help_text='Date Scheduled', null=True)),
                ('match_updated', models.DateTimeField(auto_now=True)),
                ('team_1_score', models.IntegerField(blank=True, default=0, help_text='Team 1 Score', null=True)),
                ('team_2_score', models.IntegerField(blank=True, default=0, help_text='Team 2 Score', null=True)),
                ('match_complete', models.BooleanField(blank=True, default=False, help_text='Match complete, yes or no')),
                ('contestant_1_at', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], default='H', max_length=1)),
                ('contestant_2_at', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], default='A', max_length=1)),
                ('contestant_1', models.ForeignKey(help_text='Contestant 1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestant_1', to='brackets.contestant')),
                ('contestant_2', models.ForeignKey(help_text='Contestant 2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestant_2', to='brackets.contestant')),
                ('fixture', models.ForeignKey(help_text='Part of Fixure', on_delete=django.db.models.deletion.CASCADE, to='brackets.fixture')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.fixturetype'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='fifa_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.fifateam'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='player_1',
            field=models.ForeignKey(help_text='Player 1', on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestant',
            name='player_2',
            field=models.ForeignKey(blank=True, help_text='Player 2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestant',
            name='player_3',
            field=models.ForeignKey(blank=True, help_text='Player 3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestant',
            name='player_4',
            field=models.ForeignKey(blank=True, help_text='Player 4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to=settings.AUTH_USER_MODEL),
        ),
    ]
