# Generated by Django 3.1.3 on 2020-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='TournamentSize',
            field=models.CharField(choices=[('8 Team', '8 Team'), ('16 Team', '16 Team'), ('32 Team', '32 Team')], default='Tournamentsize', max_length=120),
        ),
    ]
