# Generated by Django 3.1.3 on 2020-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0004_auto_20201204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='TournamentSize',
            field=models.CharField(choices=[('8 Teams', '8 Teams'), ('16 Teams', '16 Teams'), ('32 Teams', '32 Teams')], default='Tournamentsize', max_length=120),
        ),
    ]
