# Generated by Django 3.1.2 on 2020-10-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=120)),
                ('NrOfPlayer', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
