# Generated by Django 3.1.2 on 2020-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0002_auto_20201024_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='Player',
            field=models.TextField(default=500, max_length=500),
            preserve_default=False,
        ),
    ]
