# Generated by Django 3.1.2 on 2020-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0003_teams_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='TeamLogo',
            field=models.ImageField(default=500, upload_to=''),
            preserve_default=False,
        ),
    ]
