# Generated by Django 3.1.2 on 2020-10-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0004_teams_teamlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='TeamLogo',
        ),
    ]
