# Generated by Django 3.1.2 on 2020-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0005_remove_teams_teamlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='TeamLogo',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='Player',
            field=models.TextField(default='-', max_length=500),
        ),
    ]
