# Generated by Django 3.1.2 on 2020-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0006_auto_20201030_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='Player',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='TeamLogo',
        ),
        migrations.AddField(
            model_name='teams',
            name='Captain',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='teams',
            name='Manager',
            field=models.CharField(default='', max_length=120),
        ),
    ]
