# Generated by Django 3.1.2 on 2020-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0007_auto_20201030_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='Captain',
            field=models.CharField(default='', max_length=120),
        ),
    ]
