# Generated by Django 3.1.2 on 2020-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentOverview', '0008_auto_20201106_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TournamentName', models.CharField(max_length=120)),
                ('TournamentSize', models.CharField(choices=[('8teams', '8 Teams'), ('16teams', '16 Teams'), ('32teams', '32 Teams')], default='Tournamentsize', max_length=120)),
            ],
        ),
    ]
