# Generated by Django 3.1.3 on 2020-12-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=120)),
                ('NrOfPlayer', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Manager', models.CharField(default='', max_length=120)),
                ('Captain', models.CharField(default='', max_length=120)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournament')),
            ],
        ),
    ]
