# Generated by Django 3.1.3 on 2020-12-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_auto_20201203_1752'),
        ('Team', '0002_auto_20201203_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
