# Generated by Django 3.1.3 on 2020-12-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_auto_20201203_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('TeamName',)},
        ),
    ]
