# Generated by Django 3.1.3 on 2020-12-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_auto_20201205_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
