# Generated by Django 3.1.3 on 2020-12-05 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_auto_20201205_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='NrOfPlayer',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
