# Generated by Django 3.1.3 on 2020-12-05 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_auto_20201205_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='NrOfPlayer',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=2, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
