# Generated by Django 3.1.4 on 2020-12-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_auto_20201205_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_points', models.IntegerField(default=0)),
                ('team_b_points', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='Team.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='Team.team')),
            ],
        ),
    ]
