# Generated by Django 3.1.4 on 2020-12-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0005_auto_20201205_1017'),
        ('Team', '0008_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('1 of 32', 16), ('1 of 16', 8), ('1 of 8', 4), ('1 of 4', 2), ('1 of 2', 1)], default=('1 of 8', 4), max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournament'),
        ),
    ]
