# Generated by Django 3.1.4 on 2020-12-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0009_auto_20201208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.IntegerField(choices=[(16, '1 of 32'), (8, '1 of 16'), (4, '1 of 8'), (2, '1 of 4'), (1, '1 of 2')], default=4, max_length=50),
        ),
    ]
