# Generated by Django 3.1.4 on 2020-12-13 13:47

import Team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0010_auto_20201208_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Captain',
            field=models.CharField(default='', max_length=120, validators=[Team.models.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='team',
            name='Manager',
            field=models.CharField(default='', max_length=120, validators=[Team.models.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamName',
            field=models.CharField(max_length=120, validators=[Team.models.validate_name_length]),
        ),
    ]
